//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.Client
{
    [FUIEvent(FUIViewId.LoginForm)]
    public partial class LoginFormEventHandler : AFUIEventHandler<LoginForm>
    {
        public override string UIAssetURL => LoginForm.URL;

        protected override void OnOpen(FUI ui, LoginForm component, object userData)
        {
            component.OnOpen(ui, userData);
        }

        protected override void OnClose(FUI ui, LoginForm component)
        {
            component.OnClose(ui);
        }

        protected override void OnPause(FUI ui, LoginForm component)
        {
            component.OnPause(ui);
        }

        protected override void OnResume(FUI ui, LoginForm component)
        {
            component.OnResume(ui);
        }

        protected override void OnCover(FUI ui, LoginForm component)
        {
            component.OnCover(ui);
        }

        protected override void OnReveal(FUI ui, LoginForm component)
        {
            component.OnReveal(ui);
        }

        protected override void OnRefocus(FUI ui, LoginForm component, object userData)
        {
            component.OnRefocus(ui, userData);
        }
    }
}