//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.Client.Login
{
    [FUICompEvent(typeof(SpecialButton))]
    public partial class SpecialButtonEventHandler : AFUICompEventHandler<SpecialButton>
    {
        protected override void OnInitialize() 
        {
            ContentPane.OnInitialize();
        }

        protected override void OnDispose() 
        {
            ContentPane.OnDispose();
        }
    }
}