//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FairyGUI;

namespace ET.Client
{
    [ComponentOf(typeof(FUI))]
    public partial class LobbyForm : Entity, IAwake, IDestroy
    {
        public const string URL = "ui://if1undtbg9wi0";

        #region [子节点]
 
        public FairyGUI.GButton BtnEnter { get; set; }
 
        #endregion

        #region [控制器]

        #endregion

        #region [动效]

        #endregion
        
        /// <summary>
        /// 界面持有的CancellationToken 它会在界面被关闭时设置为取消
        /// </summary>
        public ETCancellationToken CancellationToken => this.GetParent<FUI>()?.CancellationToken;
    }
}