//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FairyGUI;

namespace ET.Client
{
    [EntitySystemOf(typeof(LobbyForm))]
    [FriendOf(typeof(LobbyForm))]
    public static partial class LobbyFormSystem
    {
		[EntitySystem]
        public static void Awake(this LobbyForm self)
        {
            FUI fui = self.GetParent<FUI>();
            GComponent contentPane = fui.ContentPane;

            #region [子节点]
 
            self.BtnEnter = (FairyGUI.GButton)contentPane.GetChildAt(0);
 
            #endregion

            #region [控制器]

            #endregion

            #region [动效]

            #endregion

            self.OnCreate(fui, contentPane);
        }

        [EntitySystem]
        public static void Destroy(this LobbyForm self)
        {
            self.OnDestroy();
        }
    }
}