//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Threading;
using FairyGUI.Utils;

namespace ET.Client.Common
{
    [FUICustomComponentAttribute(URL)]
    public partial class GameObjectComponent : FairyGUI.GComponent
    {
        public const string URL = "ui://iehegnf1g9wi0";
        
        private IFUICompEventHandler m_EventHandler;

        #region [子节点]
 
        public FairyGUI.GGraph Graph;
 
        #endregion

        #region [控制器]

        #endregion

        #region [动效]

        #endregion
        
        public override void ConstructFromXML(FairyGUI.Utils.XML xml)
        {
            base.ConstructFromXML(xml);

            #region [子节点]
 
            Graph = (FairyGUI.GGraph)GetChildAt(0);
 
            #endregion

            #region [控制器]

            #endregion

            #region [动效]

            #endregion

            m_EventHandler = FUICompEventComponent.Instance.CreateCompEventHandler(typeof(GameObjectComponent));
            m_EventHandler?.Initialize(this);
        }

        public override void Dispose()
        {
            m_EventHandler?.Dispose();
            m_EventHandler = null;
            base.Dispose();
        }
    }
}