//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Threading;

namespace ET.Client.Login
{
    [FUICustomComponentAttribute(URL)]
    public partial class SpecialButton : FairyGUI.GButton
    {
        public const string URL = "ui://gb2fsa1xun9b3";

        #region [子节点]
       
        public FairyGUI.GTextField Title;
  
        public FairyGUI.GGraph Graph;
   
        #endregion

        #region [控制器]
 
        public FairyGUI.Controller ButtonController;

        public enum ButtonControllerPage
        { 
            PageUp,
            PageDown,
            PageOver,
            PageSelectedOver,
        }

        public ButtonControllerPage CurrentButtonControllerPage
        {
            get => (ButtonControllerPage)ButtonController.selectedIndex;
            set => ButtonController.selectedIndex = (int)value;
        }
 
        #endregion

        #region [动效]

        #endregion
        
        public override void ConstructFromXML(FairyGUI.Utils.XML xml)
        {
            base.ConstructFromXML(xml);

            #region [子节点]
       
            Title = (FairyGUI.GTextField)GetChild("title");
  
            Graph = (FairyGUI.GGraph)GetChild("graph");
   
            #endregion

            #region [控制器]
 
            ButtonController = GetController("button");
 
            #endregion

            #region [动效]

            #endregion
        }
    }
}