//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.Client.Common
{
    [FUICompEvent(typeof(GameObjectComponent))]
    public partial class GameObjectComponentEventHandler : AFUICompEventHandler<GameObjectComponent>
    {
        protected override void OnInitialize() 
        {
            ContentPane.OnInitialize();
        }

        protected override void OnDispose() 
        {
            ContentPane.OnDispose();
        }
    }
}