//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FairyGUI;

namespace ET.Client
{
    [ComponentOf(typeof(FUI))]
    public partial class {{ name }} : Entity, IAwake, IDestroy
    {
        public const string URL = "{{ url }}";

        #region [子节点]
{{ for node in nodes }} {{ if is_accept_name node.name }}
        public {{ node.ref_type_full_name }} {{ upper_first node.name }} { get; set; }
{{ end }} {{ end }}
        #endregion

        #region [控制器]
{{ for controller in controllers }} {{ if is_accept_name controller.name }}
        public FairyGUI.Controller {{ upper_first controller.name }}Controller { get; set; }

        public enum {{ upper_first controller.name }}ControllerPage
        { {{ for page in controller.pages }}
            Page{{ upper_first page }},{{ end }}
        }

        public {{ upper_first controller.name }}ControllerPage Current{{ upper_first controller.name }}ControllerPage
        {
            get => ({{ upper_first controller.name }}ControllerPage){{ upper_first controller.name }}Controller.selectedIndex;
            set => {{ upper_first controller.name }}Controller.selectedIndex = (int)value;
        }
{{ end }} {{ end }}
        #endregion

        #region [动效]
{{ for transition in transitions }}  {{ if is_accept_name transition.name }}
        public FairyGUI.Transition {{ upper_first transition.name }}Transition { get; set; }
{{ end }} {{ end }}
        #endregion
    }
}