//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET.Client.{{ package_name }}
{
    [FUICompEvent(typeof({{ name }}))]
    public partial class {{ name }}EventHandler : AFUICompEventHandler<{{ name }}>
    {
        protected override void OnInitialize() 
        {
            ContentPane.OnInitialize();
        }

        protected override void OnDispose() 
        {
            ContentPane.OnDispose();
        }
    }
}